version: 2.1

jobs:
  publish:
    docker:
      - image: cimg/node:24.16.0
    resource_class: small
    steps:
      - checkout
      - run:
          name: Install
          command: |
            yarn install
      - run:
          name: Build
          command: |
            yarn build
      - run:
          name: Publish with NPM Trusted Publishing
          command: |
            export NPM_ID_TOKEN=$(circleci run oidc get --claims '{"aud": "npm:registry.npmjs.org"}')
            npm publish --access public
workflows:
  publish-npm-package:
    jobs:
      - publish:
          name: Publish package
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
